# Generated by Django 4.0.3 on 2022-03-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clubID', models.AutoField(primary_key=True, serialize=False)),
                ('clubName', models.CharField(max_length=200)),
                ('clubLogo', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=200)),
                ('countryFlag', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=200)),
                ('playerAge', models.IntegerField(default=0)),
                ('playerPhoto', models.URLField(max_length=1000)),
                ('playerPosition', models.CharField(max_length=3)),
                ('playerClub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.club')),
                ('playerCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.country')),
            ],
        ),
    ]
