# Generated by Django 4.0.3 on 2022-03-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skillsID', models.AutoField(primary_key=True, serialize=False)),
                ('prefferedFoot', models.CharField(max_length=10)),
                ('pace', models.IntegerField(default=0)),
                ('shooting', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('defending', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransferMarket',
            fields=[
                ('transferID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0, null=True)),
                ('contractExpiry', models.DateField()),
                ('wages', models.CharField(max_length=10)),
                ('releaseClause', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.skills'),
        ),
    ]
