# Generated by Django 4.0.3 on 2022-03-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0002_skills_transfermarket_player_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.skills'),
        ),
    ]
