# Generated by Django 4.0.3 on 2022-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0003_alter_player_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(null=True, to='statlist.skills'),
        ),
    ]
