# Generated by Django 4.0.3 on 2022-03-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0004_remove_player_skills_player_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statlist.skills'),
        ),
    ]
