# Generated by Django 4.0.3 on 2022-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0006_alter_transfermarket_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermarket',
            name='contractExpiry',
            field=models.IntegerField(),
        ),
    ]
