# Generated by Django 4.0.3 on 2022-03-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statlist', '0008_player_playervalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('countryName',)},
        ),
    ]
